
[custom]
;Copy自MyRules_Auto.ini基础上做简化删减,不包含“Banned.list”域名列表规则

;"🎯 全球直连"替换为"DIRECT"
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
;"🎯 全球直连"替换为"DIRECT"
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
;"🎯 全球直连"替换为"DIRECT"
ruleset=DIRECT,https://raw.githubusercontent.com/sky2016cn/Rules/main/Direct.list
;"🚀 我的代理"替换为"🚀 节点选择"
ruleset=🚀 节点选择,https://raw.githubusercontent.com/sky2016cn/Rules/main/Proxy.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Binance/Binance.list
;"Ⓜ️ 微软Bing"替换为"DIRECT"
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
;"Ⓜ️ 微软服务"替换为"DIRECT"
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
;"📢 谷歌🇨🇳Play下载"替换为"🚀 节点选择"
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
;"📢 谷歌🇨🇳Play服务"替换为"🚀 节点选择"
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
;📢 谷歌🇨🇳Play服务替换为"🚀 节点选择"
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
;"🍎 苹果服务"替换为"🚀 节点选择"
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=💬 Gemini,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list
ruleset=💬 OpenAi,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
;"🎯 全球直连"替换为"DIRECT"
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
;"🎯 全球直连"替换为"DIRECT"
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
;"🎯 全球直连"替换为"DIRECT"
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;"🎯 全球直连"替换为"DIRECT"，no-resolve 表示匹配到中国 IP 时，不进行 DNS 反查域名（性能会更好，避免多余 DNS 查询）
ruleset=DIRECT,[]GEOIP,CN,no-resolve
;第二个 GEOIP,CN,DIRECT 没有 no-resolve，上方没有配到中国 IP，会对这个中国 IP 进行 DNS 查询并再匹配，避免走最后"漏网之鱼"代理
ruleset=DIRECT,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`.*
;（注释掉）custom_proxy_group=🍎 苹果服务`select`[]🚀 节点选择`.*
;custom_proxy_group=🌍 BT`select`[]DIRECT`[]🚀 节点选择`.*
;custom_proxy_group=📲 电报信息`select`[]🚀 节点选择`.*
custom_proxy_group=💬 OpenAi`select`[]🚀 节点选择`.*
custom_proxy_group=💬 Gemini`select`[]🚀 节点选择`.*
;（注释掉）custom_proxy_group=🚀 我的代理`select`[]🚀 节点选择`.*
;（注释掉）custom_proxy_group=📢 谷歌🇨🇳Play下载`select`[]🚀 节点选择`.*
;（注释掉）custom_proxy_group=📢 谷歌🇨🇳Play服务`select`[]🚀 节点选择`.*
;（注释掉）custom_proxy_group=Ⓜ️ 微软Bing`select`[]🚀 节点选择`[]DIRECT`.*
;（注释掉）custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`.*
;（注释掉）custom_proxy_group=🎯 我的直连`select`[]DIRECT`[]🚀 节点选择`.*
;（注释掉）custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`.*
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`.*

enable_rule_generator=true
overwrite_original_rules=true
