[custom]
;此模板适用于 Chromecast
;在 MyRules_Auto.ini 基础上增加了一条国外域名规则，使规则列表数量增加了10倍：RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.list
;在 MyRules_Auto.ini 基础上增加了工行、微信、支付宝、阿里巴巴、闲鱼、京东、美团等规则

ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ICBC/ICBC.list
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat.list
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AliPay/AliPay.list
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Alibaba/Alibaba.list
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/JingDong/JingDong.list
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/XianYu/XianYu.list
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/MeiTuan/MeiTuan.list
;“🍎 AppleMail” 并入 “🎯 全球直连”
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleMail/AppleMail.list
;“我的直连” 并入 “🎯 全球直连”
ruleset=🎯 全球直连,https://raw.githubusercontent.com/sky2016cn/Rules/main/Direct.list
;“我的代理” 并入 “🚀 节点选择”
ruleset=🚀 节点选择,https://raw.githubusercontent.com/sky2016cn/Rules/main/Proxy.list
ruleset=🎥 YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
;如果无法使用GoogleTV的UI界面，将“🎥 GoogleUI”规则重新置于“🎥 YouTube”规则上方
ruleset=🎥 GoogleUI,https://raw.githubusercontent.com/sky2016cn/Rules/main/GoogleUI.list
ruleset=📢 谷歌FCM,https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=📢 谷歌🇨🇳Play服务,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=📢 谷歌🇨🇳Play服务,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=📢 谷歌🇨🇳Play服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=🎥 TVB,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TVB/TVB.list
ruleset=🎥 TVB,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBiliIntl/BiliBiliIntl.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🎥 Disney,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🎥 AppleTV,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleTV/AppleTV.list
;“🍎 苹果服务”必须在“🎥 AppleTV”下方，否则无法打开AppleTV
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🎥 USA,https://raw.githubusercontent.com/sky2016cn/Rules/main/USA.list
;“GoogleVoice” 并入 “🎥 USA”
ruleset=🎥 USA,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleVoice/GoogleVoice.list
ruleset=🎥 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=🎥 PrimeVideo,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.list
ruleset=🎥 Hulu,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hulu/Hulu.list
ruleset=🎥 HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.list
ruleset=🎥 AbemaTV,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AbemaTV/AbemaTV.list
ruleset=🎥 BBCiPlayer,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BBCiPlayer.list
ruleset=⚠️ Banned,https://raw.githubusercontent.com/sky2016cn/Rules/main/Banned.list
ruleset=🧲 BT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list
ruleset=📲 电报信息,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=💬 OpenAi,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=💬 Gemini,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list
ruleset=🚀 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=💰 币安交易,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Binance/Binance.list
ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]😎 自建节点组`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区`.*
custom_proxy_group=🎥 GoogleUI`select`[]🇺🇸 美国节点组`[]🇸🇬 新加坡节点组`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区`[]🚀 节点选择
custom_proxy_group=🎥 YouTube`select`[]🚀 节点选择`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=🎥 TVB`select`[]🇭🇰 香港节点组`(港|HK|hk|Hong Kong|HongKong|hongkong|深港)`[]🚀 节点选择
custom_proxy_group=🎥 Netflix`select`[]🚀 节点选择`[]🇸🇬 新加坡节点组`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=🎥 Disney`select`[]🚀 节点选择`[]🇸🇬 新加坡节点组`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=🎥 AppleTV`select`[]🚀 节点选择`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=🎥 USA`select`[]🇺🇸 美国节点组`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|UnitedStates)`[]🚀 节点选择
custom_proxy_group=🎥 TikTok`select`[]🚀 节点选择`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=🎥 PrimeVideo`select`[]🚀 节点选择`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=🎥 Hulu`select`[]🚀 节点选择`[]🇺🇸 美国节点组`[]🇭🇰 香港节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=🎥 HBO`select`[]🚀 节点选择`[]🇸🇬 新加坡节点组`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=🎥 AbemaTV`select`[]🚀 节点选择`[]🇸🇬 新加坡节点组`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=🎥 BBCiPlayer`select`[]🇬🇧 英国节点组`(英国|Britain|United Kingdom|England|伦敦)`[]🚀 节点选择
custom_proxy_group=⚠️ Banned`select`[]🚀 节点选择`[]😎 自建节点组`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=🧲 BT`select`[]🎯 全球直连`[]🚀 节点选择`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=🚀 GitHub`select`[]🚀 节点选择`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=💰 币安交易`select`[]🚀 节点选择`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=📲 电报信息`select`[]🚀 节点选择`[]🇸🇬 新加坡节点组`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=💬 OpenAi`select`[]🚀 节点选择`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=💬 Gemini`select`[]🚀 节点选择`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=Ⓜ️ 微软Bing`select`[]🚀 节点选择`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区`[]🎯 全球直连
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 节点选择`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=📢 谷歌🇨🇳Play服务`select`[]🚀 节点选择`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🚀 节点选择`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区
custom_proxy_group=😎 自建节点组`fallback`(P-)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=🇭🇰 香港节点组`fallback`(港|HK|hk|Hong Kong|HongKong|hongkong|深港)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=🇺🇸 美国节点组`fallback`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|UnitedStates)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=🇯🇵 日本节点组`fallback`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<!尼|-)日|JP|Japan|🇯🇵)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=🇸🇬 新加坡节点组`fallback`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=🇼🇸 台湾节点组`fallback`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=🇰🇷 韩国节点组`fallback`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=🇨🇦 加拿大节点组`fallback`(加拿大|Canada|渥太华|温哥华|卡尔加里)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=🇬🇧 英国节点组`fallback`(英国|Britain|United Kingdom|England|伦敦)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=🇫🇷 法国节点组`fallback`(法国|France|巴黎)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=🇩🇪 德国节点组`fallback`(德国|Germany|柏林|法兰克福)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=🇳🇱 荷兰节点组`fallback`(荷兰|Netherlands|阿姆斯特丹)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=🇹🇷 土耳其节点组`fallback`(土耳其|Turkey|Türkiye)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=🌐 其他地区`fallback`(^(?!.*(港|HK|hk|Hong Kong|HongKong|hongkong|深港|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|UnitedStates|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<!尼|-)日|JP|Japan|🇯🇵|新加坡|坡|狮城|SG|Singapore|台|新北|彰化|TW|Taiwan|KR|Korea|KOR|首尔|韩|韓|加拿大|Canada|渥太华|温哥华|卡尔加里|英国|Britain|United Kingdom|England|伦敦|法国|France|巴黎|德国|Germany|柏林|法兰克福|荷兰|Netherlands|阿姆斯特丹|土耳其|Turkey|Türkiye)).*)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连
;custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🇭🇰 香港节点组`[]🇺🇸 美国节点组`[]🇯🇵 日本节点组`[]🇸🇬 新加坡节点组`[]🇼🇸 台湾节点组`[]🇰🇷 韩国节点组`[]🇨🇦 加拿大节点组`[]🇬🇧 英国节点组`[]🇫🇷 法国节点组`[]🇩🇪 德国节点组`[]🇳🇱 荷兰节点组`[]🇹🇷 土耳其节点组`[]🌐 其他地区`[]🎯 全球直连

enable_rule_generator=true
overwrite_original_rules=true
